package com.redhat.agrupamento;

import java.util.HashMap;
import java.util.Map;


rule "StartProcess"

    ruleflow-group "start"
	no-loop true
	lock-on-active true

    when
        $w : Wrapper( )
    then
        System.out.println("INICIANDO PROCESSO PARA TESTE UNITARIO DO AGRUPAMENTO");
        Map params = new HashMap();
        params.put("o1", $w.getOperacao());


        insert($w.getOperacao());
        kcontext.getKnowledgeRuntime().startProcess("tesouraria.Fluxo");
        

        //create the instance, but don't start it yet
        org.kie.api.runtime.process.ProcessInstance processInstance = kcontext.getKnowledgeRuntime().createProcessInstance("tesouraria.Fluxo", params);

        //insert the instance in the WM: this will create the activation of the other rule
        insert(processInstance);

        //now, start the process
        kcontext.getKnowledgeRuntime().startProcessInstance(processInstance.getId());        

end