package com.redhat.agrupamento;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class WrapperAgrupamento implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private com.redhat.tesouraria.Operacao operacao;

   private com.redhat.impacto.Calculo calculo;

   public WrapperAgrupamento()
   {
   }

   public com.redhat.tesouraria.Operacao getOperacao()
   {
      return this.operacao;
   }

   public void setOperacao(com.redhat.tesouraria.Operacao operacao)
   {
      this.operacao = operacao;
   }

   public com.redhat.impacto.Calculo getCalculo()
   {
      return this.calculo;
   }

   public void setCalculo(com.redhat.impacto.Calculo calculo)
   {
      this.calculo = calculo;
   }

   public WrapperAgrupamento(com.redhat.tesouraria.Operacao operacao,
         com.redhat.impacto.Calculo calculo)
   {
      this.operacao = operacao;
      this.calculo = calculo;
   }

}